### ISSUE TITLE
Issue with versions and entity primary location

### ISSUE THREAD

**Issue by josephbridgwaterrowe** [westernmilling/chancellor#35]
Historical primary location details are not being show when viewing an old version of an Entity.

Change primary location relationship to a has_one with a PrimaryLocation model, polymorphic to support Customer, Vendor, and other entity types.

**Comment by josephbridgwaterrowe** [comment]
This doesn't really apply to the Entity since the locations are being moved to the related models (Customer, Salesperson, Vendor, etc.).

But this may be an issue where locations are concerned on the related models.

**Comment by josephbridgwaterrowe** [comment]
Changing location relationships to parent models to belongs_to so this may be an issue, test and update.

**Comment by michaelachrisco** [comment]
Gotcha. Let me know if you need another set of eyes.

**Comment by josephbridgwaterrowe** [comment]
This now seems to be working (at the Customer level anyway) using the belongs_to location relationship. Closing since I believe this was address in #48.

**Comment by josephbridgwaterrowe** [comment]
Final word on this, change Salesperson to belongs_to :location and use going forward with Vendor.

Closing.
